### ISSUE TITLE
Repo name?

### ISSUE THREAD

**Issue by tony** [ICTU/zap2docker-auth-weekly#44]
Thank you for the project! I have some feedback from using this.

I'm already used to the current repo name at this point but before I forget!  Would this repo be better named `zap2docker-auth-weekly`, or something else? The reason I ask is:

1. the docker image itself is `ictu/zap2docker-weekly`
2. the use of `zap-baseline` conflicts with an individual script of OWASP, but this project can (and often does) trigger `zap-api-scan.py` and `zap-full-scan.py` in addition to `zap-baseline.py` (e.g. it uses `owasp/zap2docker-weekly`)

**Comment by dicksnel** [comment]
Hi, you are right. The name was because the project started as a modified baseline scanner, but eventually evolved into an authentication hook.

I'll look at chaning the repo name. Changing the Docker image name may have more implications because many projects are already using it.

**Comment by tony** [comment]
Noted on how the project evolved from a baseline scanner! That makes sense!

Also thankfully I was just referring to the name of the github repo for this case, so changing this GH repo's name is safer since it will forward from the old name to the new one, also it won't be disruptive as the docker side of things. If you wanted to.

Should I close this for now? I assume my point has been taken (thank you!). Or it can wait until you feel fit to change the name sometime (if you ever do)

**Comment by dicksnel** [comment]
@tony change, thanks for the feedback!

**Comment by tony** [comment]
Much less ambiguous  Nice!
