### ISSUE TITLE
Chrome driver version mismatch

### ISSUE THREAD

**Issue by joshibeast** [ICTU/zap2docker-auth-weekly#47]
This started happening from last week.
The similar issue that was previously fixed:
https://github.com/ICTU/zap2docker-auth-weekly/issues/46

Current browser version is 101.0.4951.54

**Comment by dicksnel** [comment]
@joshibeast thanks, fixed in your PR! https://github.com/ICTU/zap2docker-auth-weekly/commit/12fa3b335dd54793e4bc56d935691d9537e8e87f
