### ISSUE TITLE
Saving cookies from another subdomain

### ISSUE THREAD

**Issue by mudit94** [ICTU/zap2docker-auth-weekly#52]
Hi Team,
I have a scenario like when i visit a.example.com/login , the page redirects to b.example.com wherein I give the credentials, after successfull login , it redirects back to a.example.com. As i checked , the browser cookies, it contaiains the KEYCLOAK_IDENTITY which is required for maintaining authenticated sssion. However I am unable to store this cookie key and use it for spidering. How do I achieve this authentication

**Comment by dicksnel** [comment]
Hi @mudit94, I ran into this issue myself. As far as I could see, it was not possible to set a cookie with ZAP for another domain. If you have any other idea please let me know and I'll integrate it.
