### ISSUE TITLE
assistance with authentication

### ISSUE THREAD

**Issue by DimVit23** [ICTU/zap2docker-auth-weekly#55]
Thank you for your work! Maybe you can help me!? Please tell me how to set up authentication for WebGoat? And integrate it into Jenkins work?

**Comment by dicksnel** [comment]
@DimVit23 can you take a look at the examples in the Readme: https://github.com/ICTU/zap2docker-auth-weekly

They should work with WebGoat. You can run your final command in a Jenkins Shell-script job.
