### ISSUE TITLE
How to scan multiple URLs and have only one html output report

### ISSUE THREAD

**Issue by dberardo-com** [ICTU/zap2docker-auth-weekly#58]
Is it necessary to install this plugin: https://www.zaproxy.org/docs/desktop/addons/import-urls/ and if so, how to install it programmatically and use it in the command line ?

or is this functionality already available off the shelf ?

or is there any "smart way" to achieve this via a "for loop" ?

**Comment by dicksnel** [comment]
Hi @dberardo-com, this is not supported by default.

I think the easiest way may be to loop the docker run command in a bash script.

**Comment by dberardo-com** [comment]
thanks for the prompt answer,

> I think the easiest way may be to loop the docker run command in a bash script.

but the i would end up with multiple html files, nicer would be having just a single well structured one.

 i could create a PR myself adding the plugin from above, but i could find in the ZAP documentation how plugins are installed in the first place :D any hints there ?

also as a side question: how up to date is the ZAP distribution of this project ? should we take care of updating that frequently, or does the ZAP script connects to a central database to update vulnerability definitions, etc. ?
