### ISSUE TITLE
ZAP Scan runs by default without resource limits

### ISSUE THREAD

**Issue by denniebouman** [ICTU/zap2docker-auth-weekly#69]
The ZAP Scan runs by default without resource limits, which means that all available memory can be consumed.
Recommendation: Adjust the documentation to reduce memory usage, and/or implement this in the sample scripts as well. 
This works:
docker run --rm **--memory=8g** etc..

Docker documentation: https://docs.docker.com/config/containers/resource_constraints/

**Comment by erno1978** [comment]
Added to README.txt. The complete documentation and structure of this repo needs some revision, so sample scripts will be part of that as well.
